In [1]:
# Importing required libraries & setting things.
import pandas as pd, numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Reading dataframe
data0 = pd.read_excel('orgwise_schemes_applied_2023-08-15T17_31_16.698654+05_30.xlsx')
data0.head()

,State,Org Name,Project Id,Scheme Id,status,Parent Scheme,Scheme Name,Scheme type,Fee,Timeline,Benefit Value,Open,Submitted,Received
0,Andhra Pradesh,"AP - JSW Cement '23 - '24 Nandyal, Jajpur, Sal...",PID/JSWCE/2023/DI/0308,SH0009HD,5,E-Shram Card,E-Shram Card (Central),sch,140,ਤੁਰੰਤ,1900.0,74,68.0,68.0
1,Andhra Pradesh,"AP - JSW Cement '23 - '24 Nandyal, Jajpur, Sal...",PID/JSWCE/2023/DI/0308,SH0009QJ,5,NaN,Updation of E-Shram Card (Central),sch,90,1,1900.0,35,32.0,32.0
2,Andhra Pradesh,"AP - JSW Cement '23 - '24 Nandyal, Jajpur, Sal...",PID/JSWCE/2023/DI/0308,SH0009PL,5,NaN,Work demand under MGNREGA_AP,sch,150,NaN,28900.0,101,95.0,95.0
3,Andhra Pradesh,"AP - JSW Cement '23 - '24 Nandyal, Jajpur, Sal...",PID/JSWCE/2023/DI/0308,SH00018T,5,Pradhan Mantri Suraksha Bima Yojana (PMSBY),Pradhan Mantri Suraksha Bima Yojana (Central),sch,0,NaN,9266.0,5,4.0,4.0
4,Andhra Pradesh,"AP - JSW Cement '23 - '24 Nandyal, Jajpur, Sal...",PID/JSWCE/2023/DI/0308,SH000A27,5,Pradhan Mantri Jan Arogya Yojana (Ayushman Bha...,Pradhan Mantri Jan Arogya Yojana (Ayushman Bha...,sch,0,NaN,68550.0,14,14.0,14.0

In [3]:
# Checking database information
data0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 587 entries, 0 to 586
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   State          587 non-null    object
 1   Org Name       587 non-null    object
 2   Project Id     587 non-null    object
 3   Scheme Id      587 non-null    object
 4   status         587 non-null    int64
 5   Parent Scheme  372 non-null    object
 6   Scheme Name    587 non-null    object
 7   Scheme type    587 non-null    object
 8   Fee            587 non-null    int64
 9   Timeline       293 non-null    object
 10  Benefit Value  586 non-null    float64
 11  Open           587 non-null    int64
 12  Submitted      385 non-null    float64
 13  Received       351 non-null    float64
dtypes: float64(3), int64(3), object(8)
memory usage: 64.3+ KB

In [4]:
# Checking null value counts column-wise.
data0.isnull().sum()

State              0
Org Name           0
Project Id         0
Scheme Id          0
status             0
Parent Scheme    215
Scheme Name        0
Scheme type        0
Fee                0
Timeline         294
Benefit Value      1
Open               0
Submitted        202
Received         236
dtype: int64

In [5]:
#Fill null values then convert float columns to integer.
for col in data0.columns:
    if data0[col].dtype == 'float64':
        data0[col].fillna(0.0, inplace=True)
        data0[col] = data0[col].astype('int64')
        
#Check dataframe into if above operation is successful.
data0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 587 entries, 0 to 586
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   State          587 non-null    object
 1   Org Name       587 non-null    object
 2   Project Id     587 non-null    object
 3   Scheme Id      587 non-null    object
 4   status         587 non-null    int64
 5   Parent Scheme  372 non-null    object
 6   Scheme Name    587 non-null    object
 7   Scheme type    587 non-null    object
 8   Fee            587 non-null    int64
 9   Timeline       293 non-null    object
 10  Benefit Value  587 non-null    int64
 11  Open           587 non-null    int64
 12  Submitted      587 non-null    int64
 13  Received       587 non-null    int64
dtypes: int64(6), object(8)
memory usage: 64.3+ KB

In [6]:
# Filtering with only DFL schemes
DFL = data0[(data0['Scheme Name'] == 'Digital productivity Service_ Basic') |
(data0['Scheme Name'] == 'Digital Productivity Services_Advanced') |
(data0['Scheme Name'] == 'Long Training on Digital & Financial Inclusion_Private')]

# Filtering with non-DFL schemes
Scheme = data0[(data0['Scheme Name'] != 'Digital productivity Service_ Basic') &
(data0['Scheme Name'] != 'Digital Productivity Services_Advanced') &
(data0['Scheme Name'] != 'Long Training on Digital & Financial Inclusion_Private')]

# B2C (including YKs) - DFL
DFL_YK_HESPL = DFL['Org Name'].apply(lambda x: x if ('HESPL' in x) or
                          ('Yojana' in x) or
                          ('YK' in x) else None).to_list() # Create list of B2C Org Name for DFL schemes

DFL_YK_HESPL = DFL[DFL['Org Name'] == DFL_YK_HESPL].Received.sum() # Calculating sum of benefit received for DFL - B2C Orgs
print('DFL - B2C (including YKs) = ',DFL_YK_HESPL) # Printing the value for DFL - B2C Orgs

# B2B - DFL
DFL_no_YK_HESPL = DFL['Org Name'].apply(lambda x: x if ('HESPL' not in x) or
                          ('Yojana' not in x) or
                          ('YK' not in x) else None).to_list() # Create list of B2B Org Name for DFL schemes

DFL_no_YK_HESPL = DFL[DFL['Org Name'] == DFL_no_YK_HESPL].Received.sum() # Calculating sum of benefit received for DFL - B2B Orgs
print('DFL - B2B = ',DFL_no_YK_HESPL) # Printing the value for DFL - B2B Orgs

# B2C (including YKs) - Schemes
Scheme_YK_HESPL = Scheme['Org Name'].apply(lambda x: x if ('HESPL' in x) or
                          ('Yojana' in x) or
                          ('YK' in x) else None).to_list() # Create list of B2C Org Name for non-DFL schemes

Scheme_YK_HESPL = Scheme[Scheme['Org Name'] == Scheme_YK_HESPL].Received.sum() # Calculating sum of benefit received for Non-DFL - B2C Orgs
print('Schemes - B2C (including YKs) = ',Scheme_YK_HESPL) # Printing the value for Non-DFL - B2C Orgs

# B2B - Schemes
Scheme_no_YK_HESPL = Scheme['Org Name'].apply(lambda x: x if ('HESPL' not in x) or
                          ('Yojana' not in x) or
                          ('YK' not in x) else None).to_list() # Create list of B2B Org Name for non-DFL schemes

Scheme_no_YK_HESPL = Scheme[Scheme['Org Name'] == Scheme_no_YK_HESPL].Received.sum() # Calculating sum of benefit received for Non-DFL - B2B Orgs
print('Schemes - B2B = ',Scheme_no_YK_HESPL) # Printing the value for Non-DFL - B2B Orgs

#Converting data into table
data1 = pd.DataFrame({'DFL' : [DFL_YK_HESPL,DFL_no_YK_HESPL], 'Schemes' : [Scheme_YK_HESPL,Scheme_no_YK_HESPL]}, index = ['B2C (including YKs)','B2B'])
data1

DFL - B2C (including YKs) =  0
DFL - B2B =  89607
Schemes - B2C (including YKs) =  1979
Schemes - B2B =  36065

                       DFL  Schemes
B2C (including YKs)      0     1979
B2B                  89607    36065